services:
    redis:
        container_name: radis_system_design
        image: 'bitnami/redis:6.2'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - "6379:6379"

    mariadb:
        image: mariadb
        container_name: mariadb-blatnoy
        ports:
            - "4306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123
        volumes:
            - ./docker/my-db:/var/lib/mysql
