services:

    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: ./docker/php/Dockerfile
        image: cbs_app
        container_name: blatnoy_app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        #      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        #      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        networks:
            - blatnoy


    nginx:
        image: nginx:alpine
        container_name: cbs_nginx
        restart: unless-stopped
        ports:
            - "9080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - blatnoy

    redis:
        container_name: radis_system_design
        image: 'bitnami/redis:6.2'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - "6379:6379"

    mariadb:
        image: mariadb
        container_name: mariadb-blatnoy
        ports:
            - "4306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123
        volumes:
            - ./docker/my-db:/var/lib/mysql
        networks:
            - blatnoy



networks:
    blatnoy:
        driver: bridge
